### ISSUE TITLE
How I can enable as a system proxy?

### ISSUE THREAD

**Issue by KotMilkMeoWtwo** [moqsien/neobox#1]
![Screenshot_20231224-200143_Termux~2](https://github.com/moqsien/neobox/assets/88706776/5e0a2359-de47-4e2b-a465-e4958051977f)
![Screenshot_20231224-200239_Termux](https://github.com/moqsien/neobox/assets/88706776/6e834bfc-18c2-4263-bf1b-7254b9e9f9ff)

**Comment by moqsien** [comment]
Enabling sys proxy is Currently supported on:
- Windows
- MacOS(untested)
- Linux with Gnome desktop(untested)

**Comment by KotMilkMeoWtwo** [comment]
Ok, thanks
